Set create expires 11
digitalbazaar/http-signature-zcap-invoke pull request #12
Opened 2020-10-20 12:42 UTC by aljones15

Makes created and expires parameters that can be passed in invoke while retaining the original defaults if none are passed in.

2020-10-21 14:34 UTC, dlongley requested changes

2020-10-21 14:34 UTC, dlongley commented on main.js
> + *  psuedo-header used to ensure the header expires.
```suggestion
 *   psuedo-header used in the http signature.
 * @param {string|Date|number} [options.expires] - expires is a
 *   psuedo-header used to ensure the header signature expires.
```

Not sure if our docs pattern is to be explicit with `[options.expires = undefined]` or if `[options.expires]` will do (I'm suggesting we use `undefined`, not `null` for its default).

2020-10-21 14:34 UTC, dlongley commented on main.js
> +  expires = null
```suggestion
  expires
```

2020-10-21 14:34 UTC, dlongley commented on main.js
> +  expires = null
The existing style was acceptable, btw, we didn't need to add these extra lines, but it's also ok to do.

2020-10-21 14:34 UTC, dlongley commented on main.js
> +  expires = expires || new Date(created + 600000).getTime();
I think we want to treat `created`, if it is a number, as seconds now (breaking change). Also, `created` may be a Date or string, so this will need to be tweaked to handle those cases.

2020-10-21 15:47 UTC, aljones15 commented on main.js
> +  expires = expires || new Date(created + 600000).getTime();
What do you think about having http-sigs export this: https://github.com/digitalbazaar/http-signature-header/blob/f43e5c84d3e50381bd885ce234e2732c263485fe/lib/index.js#L206-L231

and then using to check `created` and `expires` only setting defaults if it doesn't return a number?

2020-10-23 16:28 UTC, OR13 commented on main.js
> +  expires
why is expires not defaulted here as well?

2020-10-23 17:39 UTC, aljones15 commented on main.js
> +  expires
the default for expires is 10 minutes after created and I'm not sure how in a JavaScript destructuring assignment to reference another destructed parameter.

2020-12-29 19:11 UTC, OR13 commented
This PR is still blocking the creation of stable EDV test vectors.

2020-12-30 16:51 UTC, aljones15 commented on main.js
> +  expires
@OR13 do you need the ability to pass in now also for the test vectors? The http-sigs library on our side does accept a now parameter now.

2020-12-31 16:47 UTC, OR13 commented on main.js
> +  expires
yes, in general, it's nice to be able to make test vectors that are 100% pure functions, so that they can easily be implemented in other languages, and the caller has full control over the behavior.

2020-12-31 19:37 UTC, aljones15 commented on main.js
> +  expires
ok so it turns out that we do not need `now` when signing, as the actual date checking should happen in verify. This means that you can create a zcap with a `(created)` in the future for instance and sign it. I did add a PR here though that passes now to `parseRequest` so that when test vectors are created for verification, the date can be controlled: https://github.com/digitalbazaar/http-signature-zcap-verify/pull/19

2020-12-31 22:02 UTC, dlongley approved these changes

2020-12-31 22:18 UTC, aljones15 commented
NOTE: This PR needs the next release of `http-signature-header` first.

2021-01-04 18:41 UTC, OR13 approved these changes

2021-02-25 15:26 UTC, mattcollier approved these changes
TY.  I've been working with this code in new zcap work in bedrock-kms-http.  Noting there are not changelog entries included in this PR.  Perhaps it is already well known that these are breaking changes.

2021-02-25 20:06 UTC, aljones15 commented
> TY. I've been working with this code in new zcap work in bedrock-kms-http. Noting there are not changelog entries included in this PR. Perhaps it is already well known that these are breaking changes.

this was not ready for release until `http-signature-header ^2.0.0` released yesterday. I added the CHANGELOG here:
https://github.com/digitalbazaar/http-signature-zcap-invoke/pull/12/commits/8106e6fa6200f18cbbaac3ce136b1d34e87c2fdd

However we do need to discuss how to handle this release as having http-signature-header 1.0.0 on the backend and 2.0.0 on the front end and vice versa results in signatures failing to verify.

2021-02-25 20:13 UTC, mattcollier commented on CHANGELOG.md
> +- **BREAKING**: Use `http-signature-header` ^2.0.0.
From my point of view, the new defaults (mentioned under added) for created and expires being a unix timestamp (seconds since epoch) vs formerly ms since epoch should be listed as a breaking change as well.  This makes this version of the library incompatible with the older protocol unless created/expires are specified explicitly.

This was the feature that got me to using this code to begin with was to gain this new functionality.

2021-02-27 03:51 UTC, dmitrizagidulin approved these changes
:+1: 
looks reasonable. (would of course be amazing if there were unit tests for the changes).

2021-03-02 16:25 UTC, merged