Use @digitalbazaar/http-digest-header
digitalbazaar/http-signature-zcap-invoke pull request #15
Opened 2020-12-04 20:17 UTC by JSAssassin

Removed support for node 10 since it doesn't support TextEncoder.

2020-12-04 20:58 UTC, aljones15 commented
@JSAssassin can you try using this branch with a corresponding `verify` branch in a project and let me know if the http-signatures continue to work? If you don't have time I'll try  it myself.

2020-12-04 21:11 UTC, JSAssassin commented
@aljones15 I can do that, but I'm not sure which `verify` branch you are talking about and in which project?

2020-12-04 21:22 UTC, dlongley requested changes

2020-12-04 21:22 UTC, dlongley commented on main.js
> +import {createHeaderValue} from '@digitalbazaar/http-digest-header';
Move `import` up a line and keep whitespace line after it.

2020-12-04 21:22 UTC, dlongley commented on main.js
> +      {data, useMultihash: true});
```suggestion
    signed.digest = await createHeaderValue({data: json, useMultihash: true});
```

2020-12-04 21:22 UTC, dlongley commented on main.js
>      const data = new TextEncoder().encode(JSON.stringify(json));
The `createHeaderValue` library can handle this for us now, so just pass `json` to it below.

```suggestion
```

2020-12-04 21:38 UTC, dlongley approved these changes
Thanks!

2020-12-04 22:48 UTC, aljones15 approved these changes
LGTM feel free to merge.

2020-12-07 20:05 UTC, dmitrizagidulin approved these changes
👍

2020-12-07 20:06 UTC, merged